import { type Record } from './record.ts'

const COLUMNS = {
  slug: 'text',
  source_url: 'text',
  name: 'text',
  description: 'text',
  ingredients: 'jsonb',
  directions: 'jsonb',
  yield: 'text',
  nutrition: 'jsonb',
  notes: 'text',
  contributor: 'text',
} as const

const NAMES = Object.keys(COLUMNS) as (keyof typeof COLUMNS)[]

const quote = (value: string) => `'${value.replaceAll("'", "''")}'`

const rows = (records: Record[]) =>
  records.length === 0
    ? '[]'
    : `[\n${records
        .map((record) => JSON.stringify(Object.fromEntries(NAMES.map((c) => [c, record[c]]))))
        .join(',\n')}\n]`

export const statement = (records: Record[]) =>
  [
    `insert into public.recipes (${NAMES.join(', ')})`,
    `select ${NAMES.join(', ')}`,
    `from jsonb_to_recordset(${quote(rows(records))}::jsonb) as x(`,
    `  ${Object.entries(COLUMNS)
      .map(([name, type]) => `${name} ${type}`)
      .join(', ')}`,
    ')',
    // Upsert on slug, so applying the file twice is a no-op rather than a duplicate-key failure.
    'on conflict (slug) do update set',
    NAMES.slice(1)
      .map((column) => `  ${column} = excluded.${column}`)
      .join(',\n') + ';',
  ].join('\n')

export const seedSql = (records: Record[], source: string) =>
  [
    `-- Generated by \`npm run myplate:parse\` from ${source}. Do not edit by hand.`,
    `-- ${records.length} recipes from the USDA MyPlate Kitchen corpus (public domain, 17 U.S.C. § 105).`,
    '',
    statement(records),
    '',
  ].join('\n')
